spring:
  application.name: STUDENT-SERVICE

  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
    show-sql: true

  datasource:
    url: jdbc:h2:file:./students

server:
  port: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
