spring:
  application:
    name: NOTIFICATION-SERVICE
  rabbitmq:
    host: raspberrypi
    username: courseNote
    password: pass

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true