spring:
  application:
    name: NOTIFICATION-SERVICE
  rabbitmq:
    host: raspberrypi
    username: courseNote
    password: pass
  mail:
    host: smtp.gmail.com
    port: 587
    username: opiekunka81@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true